# Generated by Django 2.0.2 on 2018-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
